// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.jcornez.ruta.model.entity;

import es.jcornez.ruta.model.entity.FilterConfigBean;
import io.springlets.format.EntityFormat;

privileged aspect FilterConfigBean_Roo_DTO {
    
    declare @type: FilterConfigBean: @EntityFormat;
    
}
